
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the file
        run: |
          cd /home/runner/work/sip-hass-card/sip-hass-card/
          npm ci
          npm run build
      - name: Upload zip to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: /home/runner/work/sip-hass-card/sip-hass-card/dist/sipjs-card.js
          repo-token: ${{ secrets.GITHUB_TOKEN }}
